<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.33" />


<title>Mean and variance - Statistics</title>
<meta property="og:title" content="Mean and variance - Statistics">



  










<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/%3cnil%3e"
         width=""
         height=""
         alt="">
  </a>

  <ul class="nav-links">
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">3 min read</span>
    

    <h1 class="article-title">Mean and variance</h1>

    
    <span class="article-date">2018/02/03</span>
    

    <div class="article-content">
      <div id="mean" class="section level2">
<h2>Mean</h2>
<p>The <strong>arithemetic mean</strong> of a <em>population</em>, or <strong>population mean</strong>, is denoted <span class="math inline">\(\mu\)</span>. The <strong>sample mean</strong> is the mean of a sample of values drawn from the population.</p>
<p>The sample mean is a good estimator of the population mean. Its expected value is equal to the population mean (that is, it’s an <em>unbiased</em> estimator).</p>
<p>The sample mean is a <strong>random variable</strong>, because its value depends on the sample drawn from the population. Consequently it has its own distribution and this sampling distribution shouldn’t be confused with the original population distribution.</p>
<p>For a random sample of <span class="math inline">\(n\)</span> observations from a normally distributed population (that is, the original population is a normal distribution), the sample mean distribution (i.e. the <a href="https://en.wikipedia.org/wiki/Sampling_distribution">sampling distribution</a>) is normally distributed with mean and variance as follows:</p>
<p><span class="math display">\[\bar{x} \thicksim N\left\{\mu, \frac{\sigma^2}{n}\right\}\]</span></p>
<p>Here <span class="math inline">\(\bar{x}\)</span> denotes the random variable of sample mean. <span class="math inline">\(\mu\)</span> is the population mean and <span class="math inline">\(\sigma\)</span> is the population standard deviation.</p>
<p>Here we create a sample by drawing 100 values from a normal distribution with mean equal to 0 and standard deviation equal to 1.</p>
<pre class="r"><code>set.seed(42)
n &lt;- 100
sample_n &lt;- rnorm(n = n, mean = 0, sd = 1)
hist(sample_n)</code></pre>
<p><img src="/post/2018-02-03-mean-and-variance_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>mean(sample_n)</code></pre>
<pre><code>## [1] 0.03251482</code></pre>
<p>The mean of this one sample is already close to 0.</p>
<p>When we draw another sample with the same size, the distribution of that sample is going to look a bit different and the sample mean will differ too.</p>
<pre class="r"><code>second_sample_n &lt;- rnorm(n = n, mean = 0, sd = 1)
hist(second_sample_n)</code></pre>
<p><img src="/post/2018-02-03-mean-and-variance_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>mean(second_sample_n)</code></pre>
<pre><code>## [1] -0.08748371</code></pre>
<p>The two sample means (0.0325148 and -0.0874837) are from the sampling distribution. If we repeat this sampling process a few times, we can visualize the sampling distribution.</p>
<pre class="r"><code>set.seed(42)
times &lt;- 500
sample_distribution &lt;- vector(mode = &quot;numeric&quot;, length = times)
for (i in seq(1, times, 1)) {
  sample_distribution[i] &lt;- mean(rnorm(n = n, mean = 0, sd = 1))
}
hist(sample_distribution, breaks = 30)</code></pre>
<p><img src="/post/2018-02-03-mean-and-variance_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>We can check that the two sample means are indeed drawn from the sampling distribution.</p>
<pre class="r"><code>sample_distribution[c(1, 2)]</code></pre>
<pre><code>## [1]  0.03251482 -0.08748371</code></pre>
<p>The mean of the sampling distribution is very close to the population mean of 0.</p>
<pre class="r"><code>mean(sample_distribution)</code></pre>
<pre><code>## [1] -0.002763233</code></pre>
<p>The standard deviation of the sampling distribution is called the <a href="https://en.wikipedia.org/wiki/Standard_error">standard error</a> of the parameter (i.e., population mean). It equals the population distribution’s standard deviation divided by the squared root of sample size (100 in our example).</p>
<pre class="r"><code>sd(sample_distribution)</code></pre>
<pre><code>## [1] 0.09994498</code></pre>
<pre class="r"><code>1 / sqrt(n)</code></pre>
<pre><code>## [1] 0.1</code></pre>
<p>As we further increase the number of sampling, the mean and standard deviation of the resulting sampling distribution should approach their theoretical values.</p>
<pre class="r"><code>max_times &lt;- 5000
list_times &lt;- seq(500, max_times, 100)
list_mean &lt;- vector(mode = &quot;numeric&quot;, length = length(list_times))
list_sd &lt;- vector(mode = &quot;numeric&quot;, length = length(list_times))
set.seed(42)
for (t in seq_along(list_times)) {
  sample_distribution &lt;- vector(mode = &quot;numeric&quot;, length = list_times[t])
  for (i in seq(1, list_times[t], 1)) {
    sample_distribution[i] &lt;- mean(rnorm(n = n, mean = 0, sd = 1))
  }
  list_mean[t] &lt;- mean(sample_distribution)
  list_sd[t] &lt;- sd(sample_distribution)
}
plot(list_times, list_mean)
abline(h = 0)</code></pre>
<p><img src="/post/2018-02-03-mean-and-variance_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>plot(list_times, list_sd)
abline(h = 1 / sqrt(n))</code></pre>
<p><img src="/post/2018-02-03-mean-and-variance_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdn.bootcss.com/highlight.js//highlight.min.js"></script>



<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

